//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adm_AutoGestion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prueba {
            get {
                return ((string)(this["prueba"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public string Tiempo {
            get {
                return ((string)(this["Tiempo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00")]
        public string Id {
            get {
                return ((string)(this["Id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("foscom")]
        public string Usuario {
            get {
                return ((string)(this["Usuario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Saprouter {
            get {
                return ((string)(this["Saprouter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("foscal@foscal.com.co")]
        public string Correo {
            get {
                return ((string)(this["Correo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RjA1QzRMMjAxNyo=")]
        public string PassCorreo {
            get {
                return ((string)(this["PassCorreo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("alvaro.rincon@foscal.com.co")]
        public string Correo2000 {
            get {
                return ((string)(this["Correo2000"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Se ha realizado solicitud de certificación con funciones.")]
        public string TextoCorreo {
            get {
                return ((string)(this["TextoCorreo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.17.1.105")]
        public string Servidor {
            get {
                return ((string)(this["Servidor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string Mandante {
            get {
                return ((string)(this["Mandante"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("alvaro.rincon@foscal.com.co;andres.rincon2@gmail.com")]
        public string Correo1000 {
            get {
                return ((string)(this["Correo1000"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("alvaro.rincon@foscal.com.co;andres.rincon2@gmail.com")]
        public string Correo1000Sospechoso {
            get {
                return ((string)(this["Correo1000Sospechoso"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("alvaro.rincon@foscal.com.co;andres.rincon2@gmail.com")]
        public string Correo2000Sospechoso {
            get {
                return ((string)(this["Correo2000Sospechoso"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El colaborador mencionado a continuación reporta tener sintomas de COVID19:")]
        public string TextoCorreoSospechoso {
            get {
                return ((string)(this["TextoCorreoSospechoso"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("alvaro.rincon@foscal.com.co;andres.rincon2@gmail.com")]
        public string Correo1000Epidemiologia {
            get {
                return ((string)(this["Correo1000Epidemiologia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("alvaro.rincon@foscal.com.co;andres.rincon2@gmail.com")]
        public string Correo2000Epidemiologia {
            get {
                return ((string)(this["Correo2000Epidemiologia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("alvaro.rincon@foscal.com.co;andres.rincon2@gmail.com")]
        public string TextoCorreoEpidemiologia {
            get {
                return ((string)(this["TextoCorreoEpidemiologia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://docs.google.com/forms/d/e/1FAIpQLScX5NlL_YNEJ0T_hEytYWXCa1zgxrQDpT2ShtfrK" +
            "D_W7Ks9-w/viewform?usp=pp_url&entry.861182420=nroretiro&entry.1270610438=nombres" +
            "&entry.843183947=cedula")]
        public string Encuesta1000 {
            get {
                return ((string)(this["Encuesta1000"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Encuesta2000 {
            get {
                return ((string)(this["Encuesta2000"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextoCorreoEncuesta2000 {
            get {
                return ((string)(this["TextoCorreoEncuesta2000"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          Hola,\r\n          <br>\r\n          <br>\r\n          De manera atenta se " +
            "notifica que el empleado \r\n        ")]
        public string NotificacionIncapacidad1000 {
            get {
                return ((string)(this["NotificacionIncapacidad1000"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          Hola,\r\n          <br>\r\n          <br>\r\n          De manera atenta se " +
            "notifica que el empleado\r\n        ")]
        public string NotificacionPermiso1000 {
            get {
                return ((string)(this["NotificacionPermiso1000"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <DIV>De manera atenta se notifica que el registro de su incapacidad se encuentra en estado RECHAZADO. </DIV><br>
          <br>
          Cordialmente,
          <br>
          <H1>Servicios Digitales Foscal</H1>
          <img width=""145"" height=""156"" src=""http://www.foscal.com.co/correo/logo-correo-foscal.jpg"" alt=""Logo FOSCAL Internacional"" hspace=""5"" class=""CToWUd"">
    
        ")]
        public string NotificacionRechazoIncapacidad1000 {
            get {
                return ((string)(this["NotificacionRechazoIncapacidad1000"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<DIV>La Organización FOSCAL agradece su tiempo de vinculación laboral y le invita a diligenciar la siguiente Encuesta de Egreso Laboral:
<br>
<br>
<br>Link de Acceso:  <a href = ""https://docs.google.com/forms/d/e/1FAIpQLScX5NlL_YNEJ0T_hEytYWXCa1zgxrQDpT2ShtfrKD_W7Ks9-w/viewform?usp=pp_url&entry.861182420=nroretiro&entry.1270610438=nombres&entry.843183947=cedula"">Encuesta de Engreso</a>
<br>Le deseamos éxitos en sus nuevos proyectos
<br>
<br>
Cordialmente,
<br>Ángela Suárez Lopera
<br>Jefe División Administrativa y Talento Humano
<br>
<img width=""145"" height=""156"" src=""http://www.foscal.com.co/correo/logo-correo-foscal.jpg"" alt=""Logo FOSCAL Internacional"" hspace=""5"" class=""CToWUd"">")]
        public string TextoCorreoEncuesta1000 {
            get {
                return ((string)(this["TextoCorreoEncuesta1000"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rm9zY2FsMjAyMg==")]
        public string Contraseña {
            get {
                return ((string)(this["Contraseña"]));
            }
        }
    }
}
