// <auto-generated />
namespace Adm_AutoGestion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class campocartacesantias : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(campocartacesantias));
        
        string IMigrationMetadata.Id
        {
            get { return "202502132335074_campocartacesantias"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
